support k8s v1.10

diff --git a/image/wrapkubeadm b/image/wrapkubeadm
--- a/image/wrapkubeadm
+++ b/image/wrapkubeadm
@@ -29,11 +29,9 @@ binary_dir="/k8s"
 # FIXME: don't hardcode
 platform="linux/amd64"
 
-# These files can be either .json or .yaml depending on kubeadm version
-# (TODO: use newer kubeadm)
-apiserver_static_pod="/etc/kubernetes/manifests/kube-apiserver"
-scheduler_static_pod="/etc/kubernetes/manifests/kube-scheduler"
-controller_manager_static_pod="/etc/kubernetes/manifests/kube-controller-manager"
+apiserver_static_pod="/etc/kubernetes/manifests/kube-apiserver.yaml"
+scheduler_static_pod="/etc/kubernetes/manifests/kube-scheduler.yaml"
+controller_manager_static_pod="/etc/kubernetes/manifests/kube-controller-manager.yaml"
 
 # jq filters follow.
 # This filter updates static pod definitions to mount /hyperkube from hosts:
@@ -45,10 +43,6 @@ apiserver_insecure_bind_address='.spec.containers[0].command|=map(select(startsw
 # Make apiserver accept insecure connections on port 8080
 # TODO: don't use insecure port
 apiserver_insecure_bind_port='.spec.containers[0].command|=map(select(startswith("--insecure-port=")|not))+["--insecure-port=8080"]'
-
-# Enable MountPropagation in api
-# FIXME: It deletes other enabled gates
-apiserver_mount_propagation='.spec.containers[0].command|=map(select(startswith("--feature-gates=")|not))+["--feature-gates=MountPropagation=true"]'
 
 function dind::cluster-cidr {
   if [[ ! -e "/v6-mode" ]]; then
@@ -116,10 +110,18 @@ function dind::get-binary-from-url {
 function dind::get-binary {
   local filename="$1"
   local src="$2"
+
   if [[ ${src} = "build://" ]]; then
     dind::get-binary-from-build-data-container "${filename}"
   elif [[ ${src} = "keep://" ]]; then
     dind::verify-binary "${filename}"
+  elif [[ ${src} = gs://* ]]; then
+    if [ ! -d "google-cloud-sdk" ]
+    then
+      dind::install-google-cloud-sdk
+    fi
+    ./google-cloud-sdk/bin/gsutil cp ${src} ${binary_dir}
+    chmod 755 ${binary_dir}/${filename}
   else
     dind::get-binary-from-url "${filename}" "${src}"
   fi
@@ -137,16 +139,26 @@ function dind::image-exists {
   fi
 }
 
+function dind::install-google-cloud-sdk {
+  cd
+  apt-get -y install wget python
+  wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-186.0.0-linux-x86_64.tar.gz
+  tar -xvf ./google-cloud-sdk-186.0.0-linux-x86_64.tar.gz
+  ./google-cloud-sdk/install.sh -q
+  rm ./google-cloud-sdk-186.0.0-linux-x86_64.tar.gz
+}
+
+
 function dind::ensure-binaries-and-hypokube {
   # avoid race - if binaries need to be fetched,
   # do it in just one container
-  if [[ ${is_master} ]]; then
+  if [[ ${is_master} ]] || [[ ${HYPERKUBE_SOURCE} = gs://* ]]; then
      dind::get-binaries
   fi
   local hyperkube_bin="${binary_dir}/hyperkube"
   # in prebuilt (complete) DIND images, final hypokube image is
   # already present
-  if ! dind::image-exists "${hypokube_final_image}" || [[ ${HYPERKUBE_SOURCE} = build:// ]] ; then
+  if ! dind::image-exists "${hypokube_final_image}" || [[ ${HYPERKUBE_SOURCE} = build:// ]] || [[ ${HYPERKUBE_SOURCE} = gs://* ]] ; then
     # We use current hyperkube binary to build final hypokube image.
     # It will be used for initial cluster deployment.
     # After we "frob" the cluster, the hyperkube image is taken from /k8s directory.
@@ -178,32 +190,19 @@ function dind::yq {
   rm -f "${tmp}"
 }
 
-function dind::jq {
-  local filter="$1"
-  local path="$2"
-  jq "${filter}" "${path}" | dind::replace "${path}"
-}
-
 function dind::join-filters {
   local IFS="|"
   echo "$*"
 }
 
 function dind::frob-file {
-  local path_base="$1"
+  local path="$1"
   shift
   local filter="$(dind::join-filters "$@")"
   local status=0
-  if [[ -f ${path_base}.json ]]; then
-    dind::jq "${filter}" "${path_base}.json" || status=$?
-  elif [[ -f ${path_base}.yaml ]]; then
-    dind::yq "${filter}" "${path_base}.yaml" || status=$?
-  else
-    echo "${path_base}.json or ${path_base}.yaml not found" >&2
-    return 1
-  fi
+  dind::yq "${filter}" "${path}" || status=$?
   if [[ ${status} -ne 0 ]]; then
-    echo "Failed to frob ${path_base}.json or ${path_base}.yaml" >&2
+    echo "Failed to frob ${path}" >&2
     return 1
   fi
 }
@@ -232,8 +231,11 @@ function dind::frob-proxy-configmap {
   # Use a simple hack described in comments for
   # https://github.com/kubernetes/kubernetes/issues/30558
   # to replace just one key in the configmap
+  # In k8s 1.10, 'kubectl create configmap --dry-run' doesn't set apiVersion
+  # and kind for some reason (they are required for 'kubectl apply').
   kubectl create configmap \
-          -n kube-system --dry-run -o yaml --from-file=config.conf="${conffile}" kube-proxy |
+          -n kube-system --dry-run -o json --from-file=config.conf="${conffile}" kube-proxy |
+          jq '.apiVersion="v1"|.kind|="ConfigMap"' |
     kubectl apply -f -
 
   # only remove the temp dir (inside the container) if the
@@ -253,7 +255,7 @@ function dind::frob-proxy {
 
   # sometimes this fails with 'the server doesn't have a resource type "daemonsets"'
   # if done too early
-  dind::retry kubectl -n kube-system get ds -l k8s-app=kube-proxy -o name >/dev/null
+  dind::retry kubectl -n kube-system get ds kube-proxy >/dev/null
 
   local filters
   # in case if the configmap is used, command line args will be overridden by it
@@ -267,15 +269,11 @@ function dind::frob-proxy {
   kubectl -n kube-system get ds -l k8s-app=kube-proxy -o json |
     jq "${filters}" |
     kubectl apply --force -f -
-  kubectl -n kube-system delete pods --now -l "k8s-app=kube-proxy"
+  kubectl -n kube-system delete pods --now -l "k8s-app=kube-proxy" || true
 }
 
 function dind::frob-apiserver {
-  if ! /k8s/hyperkube kubelet --version | grep -q 'v1\.7\.'; then
-    local -a filters=("${mount_binaries}" "${apiserver_insecure_bind_address}" "${apiserver_insecure_bind_port}" "${apiserver_mount_propagation}")
-  else
-    local -a filters=("${mount_binaries}" "${apiserver_insecure_bind_address}" "${apiserver_insecure_bind_port}")
-  fi
+  local -a filters=("${mount_binaries}" "${apiserver_insecure_bind_address}" "${apiserver_insecure_bind_port}")
   dind::frob-file "${apiserver_static_pod}" "${filters[@]}"
 }
 
@@ -294,11 +292,8 @@ function dind::num-apiserver-restarts {
 function dind::wait-for-apiserver {
     local docker_ip="$(ip addr show docker0 | grep -w inet | awk '{ print $2; }' | sed 's@/.*@@')"
     local url="http://${docker_ip}:8080/api"
-    local n=60
-    while true; do
-      if curl -s "${url}" >&/dev/null; then
-        break
-      fi
+    local n=180
+    while ! curl -s "${url}" >&/dev/null; do
       if ((--n == 0)); then
         echo "Error: timed out waiting for apiserver to become available" >&2
       fi
@@ -307,23 +302,31 @@ function dind::wait-for-apiserver {
 }
 
 function dind::frob-cluster {
+  systemctl stop kubelet
+  docker ps -a -q --filter=label=io.kubernetes.pod.uid | while read container_id; do
+    docker rm -f "${container_id}"
+  done
   dind::frob-apiserver
   dind::frob-scheduler
   dind::frob-controller-manager
+  start_services kubelet
   dind::wait-for-apiserver
   dind::frob-proxy
 }
 
-kubelet_dind_args=()
+KUBELET_FEATURE_GATES=${KUBELET_FEATURE_GATES:-none}
+if [ "${KUBELET_FEATURE_GATES}" != "none" ]; then
+  kubelet_dind_args=(--fail-swap-on=false
+                     --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf
+                     --feature-gates=${KUBELET_FEATURE_GATES} )
+else
+  kubelet_dind_args=(--fail-swap-on=false
+                     --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf )
+fi
 
-function dind::maybe-use-bootstrap-kubeconfig {
-  # New behavior to be used after https://github.com/kubernetes/kubernetes/pull/49681
-  # Don't use --bootstrap-kubeconfig for k8s 1.7 though
-  if ! /k8s/hyperkube kubelet --help 2>&1 | grep -q -- --bootstrap-kubeconfig || /k8s/hyperkube kubelet --version | grep -q 'v1\.7\.'; then
-    return
-  fi
-  kubelet_dind_args+=(--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf)
-}
+if [ -n "${POD_INFRA_CONTAINER_IMAGE}" ];then
+  kubelet_dind_args+=(--pod-infra-container-image=${POD_INFRA_CONTAINER_IMAGE})
+fi
 
 function dind::fix-cgroups {
   # Workaround for https://github.com/kubernetes/kubernetes/issues/43704
@@ -336,27 +339,8 @@ function dind::fix-cgroups {
   kubelet_dind_args+=(--cgroups-per-qos=false --enforce-node-allocatable=)
 }
 
-function dind::maybe-enable-swap {
-  if ! /k8s/hyperkube kubelet --help 2>&1 | grep -q -- --fail-swap-on; then
-    return
-  fi
-  kubelet_dind_args+=("--fail-swap-on=false")
-}
-
-function dind::enable-feature-gates {
-  # Mount propagation was added in 1.8, don't use it in k8s
-  if ! /k8s/hyperkube kubelet --version | grep -q 'v1\.7\.'; then
-    kubelet_dind_args+=(--feature-gates=DynamicKubeletConfig=true,MountPropagation=true)
-  else
-    kubelet_dind_args+=(--feature-gates=DynamicKubeletConfig=true)
-  fi
-}
-
 function dind::set-kubelet-dind-args {
-  dind::maybe-use-bootstrap-kubeconfig
   dind::fix-cgroups
-  dind::maybe-enable-swap
-  dind::enable-feature-gates
   if [[ ${#kubelet_dind_args[@]} -gt 0 ]]; then
     sed -i "s@KUBELET_DIND_ARGS=@KUBELET_DIND_ARGS=${kubelet_dind_args[*]}@" /lib/systemd/system/kubelet.service
   fi
@@ -384,11 +368,19 @@ function dind::prepare-for-kubeadm {
   systemctl enable kubelet
 }
 
+function dind::kubeadm-reset {
+  if kubeadm reset --help 2>/dev/null|grep -q -- --force; then
+    kubeadm reset --force || true
+  else
+    kubeadm reset || true
+  fi
+}
+
 function dind::do-kubeadm {
   if ! time KUBE_HYPERKUBE_IMAGE="${hypokube_final_image}" kubeadm "$@"; then
     echo "*** 'kubeadm $*' failed, doing kubeadm reset ***" >&2
     cp -av /etc/cni /etc/cni.bak
-    kubeadm reset || true
+    dind::kubeadm-reset
     rm -rf /etc/cni
     mv /etc/cni.bak /etc/cni
     systemctl restart kubelet
